### ISSUE TITLE
Event filtering

### ISSUE THREAD

**Issue by AnaCarrizales** [BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos#20]
### Tasks

- [ ] The application must offer the user the option to filter events according to different criteria:

     - [ ] By event type: public or private

     - [ ]  By event date: on a particular date or in a range of dates.
