### ISSUE TITLE
Create event list screen

### ISSUE THREAD

**Issue by AnaCarrizales** [BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos#3]
### Tasks

- [ ] When selecting the "Start" option from the menu, the application should redirect the user to a new screen.
- [ ] On this screen, all registered events should be displayed.
- [ ] For each event, the following details should be displayed:
**Title:** The title of the event.
**Description:** The description of the event.
**Date:** The date of the event.
**Location:** The location of the event.
**Cost:** The cost of the event.
